### PR TITLE
Updated website

### PR DESCRIPTION
**Pull request by jlam55555**
Used the newest code from the other repo

### CODE REVIEW

**Comment by junewunder** [comment]
Why did you delete .gitignore?

**Comment by junewunder** [comment]
This is pretty nitpicky: Make sure you're using spaces, not tabs in your editor. Atom will take care of that for you.

**Comment by jlam55555** [comment]
Oops-- I didn't mean to delete .gitignore. I'll add that back in

**Comment by jlam55555** [comment]
And why spaces? I'm using Vim right now, so I use tabs. Does it really matter? It worked before with tabs.

**Comment by junewunder** [comment]
spaces are just convention, here's a styleguide that I like http://nodeguide.com/style.html

> Let's start with the religious problems first. Our benevolent dictator has chosen 2 space indention for the node core, so you would do well to follow his choice.

It's just good to have a contiguous style throughout different files

**Comment by junewunder** [comment]
@jlam55555 why replace `header` with `div#header`?  I fixed it in my commit

**Pull request merged**
